### ISSUE TITLE
Missing lwt_ssl dependency

### ISSUE THREAD

**Issue by cuihtlauac** [MagnusS/okra#115]
Here is the error I had this morning:
```sh
>okra generate --week=41 > weekly/2022/41/cuihtlauac.md
okra: internal error, uncaught exception:
      Failure("No SSL or TLS support compiled into Conduit")
```

In order to reach that point, I had previously decided to install `okra` in a switch inside the `tarides/admin` project. 

Here is what I had done (I'm using Ubuntu 22.04 and tcsh): 
```sh
cd admin
opam switch create ./
eval `opam env`
opam pin -y https://github.com/MagnusS/okra.git#release
eval `opam env`
``` 
Then, the above command failed.

I worked around the issue by executing:
```sh
opam install lwt_ssl
```
Which allowed me to generate my report.

Is the project missing a dependency?

**Comment by cuihtlauac** [comment]
Corresponding PR: https://github.com/MagnusS/okra/pull/116

**Comment by patricoferris** [comment]
Fixed in the PR, thanks!
