### ISSUE TITLE
Support (New WI) syntax

### ISSUE THREAD

**Issue by jmid** [MagnusS/okra#133]
Following the move from tracking Key Results (KRs) to Work Items (WIs) it would be nice:tm: to have `okra` support `(New WI)` indicators.

**Comment by jmid** [comment]
Here's an example weekly.md:
```
# Last Week

- Foo the bar (New WI)
  - @engineer (2 days)
  - Some more fooing to make the bar work on #1234
```

which gives rise to this linting error:
```
$ okra lint -e /tmp/weekly.md 
[ERROR(S)]: /tmp/weekly.md

In KR "Foo the bar (New WI)":
  No KR ID found. WIs should be in the format "This is a WI (#123)", where 123 is the WI issue ID. Legacy KRs should be in the format "This is a KR (PLAT123)", where PLAT123 is the KR ID. have an ID yet, use "New KR" and for work without a KR use "No KR".
```

Do we want to go a step further and support `(No WI)` too?

**Comment by tmcgilchrist** [comment]
Also adding support for the new WIs to `okra cat --engineer` which I use to generate weekly / monthly reporting.
