### ISSUE TITLE
Add the repository name in PR link

### ISSUE THREAD

**Issue by tmattio** [MagnusS/okra#23]
This is useful when generating issues and PRs from multiple repositories. For instance `#75` can become `ocaml/ood#75`

**Comment by patricoferris** [comment]
Thanks for the feedback @tmattio, completely agree. Do you think items should also contain what type of activity they are that is clearer to those reading the rendered markdown. For example in my last report I had two items like: 

```
- add okra mdx examples [#19](https://github.com/MagnusS/okra/pull/19)
- Improve documentation of the binary [#18](https://github.com/MagnusS/okra/issues/18)
```

Do you think something like this is better? (Whether something is an issue, review or PR is captured by the URL but I'm thinking more for people reading the formatted markdown)

```
- PR: add okra mdx examples [MagnusS/okra#19](https://github.com/MagnusS/okra/pull/19)
- Issue: Improve documentation of the binary [MagnusS/okra#18](https://github.com/MagnusS/okra/issues/18)
```

**Comment by tmattio** [comment]
It would be useful as well! With the category of issue, it's probably easier to identify the ones that don't need to be kept (e.g. 90% of the issues don't need an entry in my reports, they are mostly just comments that didn't take much time)

**Comment by patricoferris** [comment]
Thanks, better looking at them than looking for them I guess :))
