### ISSUE TITLE
Shorten GitHub URLs (configurable option?)

### ISSUE THREAD

**Issue by dra27** [MagnusS/okra#31]
The code is probably in get-activity, but I expect this would want to be configurable. When reading raw markdown in the one true editor, I prefer to put `user/repo#nnnn` rather than `[user/repo#nnnn](https://github.com/user/repo/pull/nnnn)` just for brevity (esp. as GitHub web interface recognises it anyway in short-form).

**Comment by patricoferris** [comment]
I started implementing this, but I'm little unsure at which stage you want this added. I initially assumed something like `okra generate --week=37 --no-links` which would render the Github links as you described, is that about right or do you want the links transformed when aggregated?

**Comment by dra27** [comment]
Oo, both if it can be done at aggregation, too, please! 🙂 I only asked in `generate` initially because I realise that _converting_ the URLs is more involved than generating them. Links such as `[I did this change here](https://github.com/user/repo/pull/n)` don't want to lose the text whereas `[#nn](https://...)` or `[user/repo#nnn](https://....)` both do.

**Comment by patricoferris** [comment]
Thank @tmcgilchrist, this is now merged 🎉
