### ISSUE TITLE
okra cat niggles

### ISSUE THREAD

**Issue by dra27** [MagnusS/okra#38]
```
mkdir -p /tmp/okra-repro
cd /tmp/okra-repro
git clone git@github.com:tarides/admin.git tarides
git clone git@github.com:ocamllabs/admin.git oclc
cd tarides
git checkout 212b71dc95dcf85f3f5cbbbfd3ec178bda1c4264
cd ../oclc
git checkout 735bc20c6a556436e36bd099aaa3e7060bbd052c
cd ..
cat tarides/weekly/2021/31/{antonin,smorimoto,tmcgilchrist}.md oclc/weekly/2021/31/{dra27,Kate,talex5,patrick}.md 2>/dev/null  | okra cat -e
```
(and also for 32-35). A few things:

- Continuation lines are being lost within a bullet: in w31 Plat88 for example, not the line "Malcolm says..." which is part of the previous bullet
- Levels of bullets are being clobbered (cf. Plat138 w31)
- All the reports have two L1 headings "Last Week" followed by another L2 "Last Week" sub-heading?
- It'd be slightly nicer for `2 days` vs `2.00 days` (and where needed, `0.5 days` vs `0.50 days`) while our granularity stays at ½ days
- Capitalising KR codes? (`PLAT105` vs `Plat105`)

**Comment by MagnusS** [comment]
#37 should improve some if this (KR capitalisation and time)

The other issues:
- [ ] "Last Week" L2/L1 header appearing multiple times in the output although it's the same for each KR
- [ ] Bullet indentation lost after 3 levels:

```
- My KR (id1)
  - @engineer1 (x days)
  - Some work
    - Details
      - More details
```
becomes
```
- My KR (id1)
  - @engineer1 (x days)
  - Some work
    - Details
    - More details
```

- [ ] Continuation broken: 

```
- Bullet1
  More details
- Bullet2
```
becomes
```
- Bullet1
More details
- Bullet2
```

**Comment by dra27** [comment]
Oh, I think it might have been that the OKRs don't aggregate if the title differs slightly (but the OKR number is the same)

**Comment by MagnusS** [comment]
Formatting was improved in #53 and should fix the issues mentioned here
