### ISSUE TITLE
cat is confused when the same KR id has different names

### ISSUE THREAD

**Issue by emillon** [MagnusS/okra#56]
Hi,

When different input reports refer to the same KR via different names (but the same id), `okra cat` outputs different sections.
This can happen when a KR is renamed and some users use the old name.

The following cram test outlines the issue:

    $ okra cat --engineer << EOF
    > # Last week
    > 
    > - KR1 name (KR1)
    >   - @a (1 day)
    >   - info about KR1
    > 
    > # Last week
    > 
    > - Another name for KR1 (KR1)
    >   - @b (1 day)
    >   - other info about KR1
    > EOF
    # Last week
    
    ## Last week
    
    - Another name for KR1 (KR1)
      - @b (1 day)
      - other info about KR1
    
    - KR1 name (KR1)
      - @a (1 day)
      - info about KR1

In terms of behavior I think it's fine to just pick one (especially if at the end we emit the final report by merging into a "gold" template - which is what I'm doing by hand for now). Or emitting a warning or an error could be useful too.

**Comment by MagnusS** [comment]
This was intentional in case a KR was renamed, but it probably makes more sense to combine under the last name. With #41 we could also set the title automatically later.

**Comment by MagnusS** [comment]
#53 should fix this when it's ready

**Comment by MagnusS** [comment]
A test and fix for this was added in #53
