### ISSUE TITLE
okra cat --append to add late reports

### ISSUE THREAD

**Issue by dra27** [MagnusS/okra#87]
It should work already via a temporary file, but it would be useful to be able to issue something like `okra cat -e --append team-weeklies/2021/44/dra27.md oclc/weekly/2021/44/dra27.md` and have the naughty team lead's report added to the already-created aggregate. Perhaps the lines added could even be marked as new (although I can use `git diff` for that)

**Comment by MagnusS** [comment]
Ah, so this would be a replacement for something like the following?

```
# Create team report
$ okra cat --engineer eng-report1.md eng-report2.md > team-report.md

# Late report appears, add to team-report.md
$ okra cat --engineer late-report.md > temp.md
$ okra cat --team team-report.md temp.md -i team-report.md
```

With an `--append-to [weekly-report]` you could instead do something like:
```
# Create team report
$ okra cat --engineer eng-report1.md eng-report2.md > team-report.md

# Late report appears, add to team-report.md
$ okra cat --engineer late-report.md --append-to team-report.md
<diff shown>
```
(assuming `--append-to` did the update in-place)

**Comment by MagnusS** [comment]
Maybe it's better to let the output go to stdout by default and then use the existing `-i` if you want to replace the team report.

**Comment by dra27** [comment]
Yes, that sounds perfect - I hadn't spotted `-i` so having a way to merge the second two commands with `--append-to <next-level-up-aggregate>` and then `-i` to confirm the change sounds excellent, thanks!
