### ISSUE TITLE
No okra command in PATH

### ISSUE THREAD

**Issue by OlivierNicole** [MagnusS/okra#97]
After installing okra, I still have no executable named `okra` in my `$PATH`.

## Steps to reproduce

Optional, but I verified that the problem still appears from a clean switch:
```
opam switch remove 4.13.1
opam switch create 4.13.1
```

Then:
```
opam pin okra https://github.com/magnuss/okra.git#release
```

This is all the more troubling that okra worked well last week, I broke it trying to update it, and now it won't work again…

**Comment by MagnusS** [comment]
Okra consists of two packages - a library and a binary. To install both, just remove the "okra" reference and it should work (this is the command from the README):

```
opam pin -y https://github.com/MagnusS/okra.git#release
```

alternatively

```
opam pin okra https://github.com/MagnusS/okra.git#release
opam pin okra-bin https://github.com/MagnusS/okra.git#release
```

**Comment by OlivierNicole** [comment]
Ah, this makes sense, thank you. Can I make a PR on your README so that others do not make the same mistake as me?

**Comment by MagnusS** [comment]
@OlivierNicole yes that would probably be a useful clarification :-) Thanks
